name: Deploy Static Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: codebuild-Notes-${{ github.run_id }}-${{ github.run_attempt }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://rakshit-notes-website --exclude ".git/*" --delete
